#!/bin/bash
#@ job_name = train_rsnns
#@ initialdir = .
#@ output = train_rsnns_%j.out
#@ error = train_rsnns_%j.err
#@ total_tasks = 1
#@ cpus_per_task = 1
#@ wall_clock_limit = 24:00:00

R-3.1.3/bin/Rscript train_rsnns.R
